package org.domain.moneda.entity;

// Generated 27/04/2015 11:47:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Agencia generated by hbm2java
 */
@Entity
@Table(name = "agencia")
public class Agencia implements java.io.Serializable {

	private String nombre;

	public Agencia() {
	}

	public Agencia(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@Column(name = "nombre", unique = true, nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
