package org.domain.moneda.entity;

// Generated 7/10/2015 05:14:39 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * AuditGastosId generated by hbm2java
 */
@Embeddable
public class AuditGastosId implements java.io.Serializable {

	private String documento;
	private Date fecha;
	private Long valor;
	private String observacion;
	private String tipogasto;
	private int consecutivo;
	private BigDecimal valorbolivar;
	private String usuariomod;
	private Date fechamod;

	public AuditGastosId() {
	}

	public AuditGastosId(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public AuditGastosId(String documento, Date fecha, Long valor,
			String observacion, String tipogasto, int consecutivo,
			BigDecimal valorbolivar, String usuariomod, Date fechamod) {
		this.documento = documento;
		this.fecha = fecha;
		this.valor = valor;
		this.observacion = observacion;
		this.tipogasto = tipogasto;
		this.consecutivo = consecutivo;
		this.valorbolivar = valorbolivar;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	@Column(name = "documento", length = 15)
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "valor", precision = 14, scale = 0)
	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	@Column(name = "observacion", length = 200)
	@Length(max = 200)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "tipogasto", length = 2)
	@Length(max = 2)
	public String getTipogasto() {
		return this.tipogasto;
	}

	public void setTipogasto(String tipogasto) {
		this.tipogasto = tipogasto;
	}

	@Column(name = "consecutivo", nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "valorbolivar", precision = 5, scale = 3)
	public BigDecimal getValorbolivar() {
		return this.valorbolivar;
	}

	public void setValorbolivar(BigDecimal valorbolivar) {
		this.valorbolivar = valorbolivar;
	}

	@Column(name = "usuariomod", length = 20)
	@Length(max = 20)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Column(name = "fechamod", length = 22)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditGastosId))
			return false;
		AuditGastosId castOther = (AuditGastosId) other;

		return ((this.getDocumento() == castOther.getDocumento()) || (this
				.getDocumento() != null
				&& castOther.getDocumento() != null && this.getDocumento()
				.equals(castOther.getDocumento())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& ((this.getValor() == castOther.getValor()) || (this
						.getValor() != null
						&& castOther.getValor() != null && this.getValor()
						.equals(castOther.getValor())))
				&& ((this.getObservacion() == castOther.getObservacion()) || (this
						.getObservacion() != null
						&& castOther.getObservacion() != null && this
						.getObservacion().equals(castOther.getObservacion())))
				&& ((this.getTipogasto() == castOther.getTipogasto()) || (this
						.getTipogasto() != null
						&& castOther.getTipogasto() != null && this
						.getTipogasto().equals(castOther.getTipogasto())))
				&& (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getValorbolivar() == castOther.getValorbolivar()) || (this
						.getValorbolivar() != null
						&& castOther.getValorbolivar() != null && this
						.getValorbolivar().equals(castOther.getValorbolivar())))
				&& ((this.getUsuariomod() == castOther.getUsuariomod()) || (this
						.getUsuariomod() != null
						&& castOther.getUsuariomod() != null && this
						.getUsuariomod().equals(castOther.getUsuariomod())))
				&& ((this.getFechamod() == castOther.getFechamod()) || (this
						.getFechamod() != null
						&& castOther.getFechamod() != null && this
						.getFechamod().equals(castOther.getFechamod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getValor() == null ? 0 : this.getValor().hashCode());
		result = 37
				* result
				+ (getObservacion() == null ? 0 : this.getObservacion()
						.hashCode());
		result = 37 * result
				+ (getTipogasto() == null ? 0 : this.getTipogasto().hashCode());
		result = 37 * result + this.getConsecutivo();
		result = 37
				* result
				+ (getValorbolivar() == null ? 0 : this.getValorbolivar()
						.hashCode());
		result = 37
				* result
				+ (getUsuariomod() == null ? 0 : this.getUsuariomod()
						.hashCode());
		result = 37 * result
				+ (getFechamod() == null ? 0 : this.getFechamod().hashCode());
		return result;
	}

}
