package org.domain.moneda.entity;

// Generated 7/10/2015 05:14:39 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * AuditTransferenciaId generated by hbm2java
 */
@Embeddable
public class AuditTransferenciaId implements java.io.Serializable {

	private int consecutivo;
	private BigDecimal preciobolivar;
	private String tipobolivar;
	private Long valorbolivar;
	private String numcuenta;
	private String numcuentapromotor;
	private String documentopromotor;
	private BigDecimal preciocompra;
	private BigDecimal precioasesor;
	private String usuariomod;
	private Date fechamod;

	public AuditTransferenciaId() {
	}

	public AuditTransferenciaId(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public AuditTransferenciaId(int consecutivo, BigDecimal preciobolivar,
			String tipobolivar, Long valorbolivar, String numcuenta,
			String numcuentapromotor, String documentopromotor,
			BigDecimal preciocompra, BigDecimal precioasesor,
			String usuariomod, Date fechamod) {
		this.consecutivo = consecutivo;
		this.preciobolivar = preciobolivar;
		this.tipobolivar = tipobolivar;
		this.valorbolivar = valorbolivar;
		this.numcuenta = numcuenta;
		this.numcuentapromotor = numcuentapromotor;
		this.documentopromotor = documentopromotor;
		this.preciocompra = preciocompra;
		this.precioasesor = precioasesor;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	@Column(name = "consecutivo", nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "preciobolivar", precision = 5)
	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	@Column(name = "tipobolivar", length = 3)
	@Length(max = 3)
	public String getTipobolivar() {
		return this.tipobolivar;
	}

	public void setTipobolivar(String tipobolivar) {
		this.tipobolivar = tipobolivar;
	}

	@Column(name = "valorbolivar", precision = 12, scale = 0)
	public Long getValorbolivar() {
		return this.valorbolivar;
	}

	public void setValorbolivar(Long valorbolivar) {
		this.valorbolivar = valorbolivar;
	}

	@Column(name = "numcuenta", length = 25)
	@Length(max = 25)
	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	@Column(name = "numcuentapromotor", length = 25)
	@Length(max = 25)
	public String getNumcuentapromotor() {
		return this.numcuentapromotor;
	}

	public void setNumcuentapromotor(String numcuentapromotor) {
		this.numcuentapromotor = numcuentapromotor;
	}

	@Column(name = "documentopromotor", length = 15)
	@Length(max = 15)
	public String getDocumentopromotor() {
		return this.documentopromotor;
	}

	public void setDocumentopromotor(String documentopromotor) {
		this.documentopromotor = documentopromotor;
	}

	@Column(name = "preciocompra", precision = 5)
	public BigDecimal getPreciocompra() {
		return this.preciocompra;
	}

	public void setPreciocompra(BigDecimal preciocompra) {
		this.preciocompra = preciocompra;
	}

	@Column(name = "precioasesor", precision = 5)
	public BigDecimal getPrecioasesor() {
		return this.precioasesor;
	}

	public void setPrecioasesor(BigDecimal precioasesor) {
		this.precioasesor = precioasesor;
	}

	@Column(name = "usuariomod", length = 20)
	@Length(max = 20)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Column(name = "fechamod", length = 22)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditTransferenciaId))
			return false;
		AuditTransferenciaId castOther = (AuditTransferenciaId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getPreciobolivar() == castOther.getPreciobolivar()) || (this
						.getPreciobolivar() != null
						&& castOther.getPreciobolivar() != null && this
						.getPreciobolivar()
						.equals(castOther.getPreciobolivar())))
				&& ((this.getTipobolivar() == castOther.getTipobolivar()) || (this
						.getTipobolivar() != null
						&& castOther.getTipobolivar() != null && this
						.getTipobolivar().equals(castOther.getTipobolivar())))
				&& ((this.getValorbolivar() == castOther.getValorbolivar()) || (this
						.getValorbolivar() != null
						&& castOther.getValorbolivar() != null && this
						.getValorbolivar().equals(castOther.getValorbolivar())))
				&& ((this.getNumcuenta() == castOther.getNumcuenta()) || (this
						.getNumcuenta() != null
						&& castOther.getNumcuenta() != null && this
						.getNumcuenta().equals(castOther.getNumcuenta())))
				&& ((this.getNumcuentapromotor() == castOther
						.getNumcuentapromotor()) || (this
						.getNumcuentapromotor() != null
						&& castOther.getNumcuentapromotor() != null && this
						.getNumcuentapromotor().equals(
								castOther.getNumcuentapromotor())))
				&& ((this.getDocumentopromotor() == castOther
						.getDocumentopromotor()) || (this
						.getDocumentopromotor() != null
						&& castOther.getDocumentopromotor() != null && this
						.getDocumentopromotor().equals(
								castOther.getDocumentopromotor())))
				&& ((this.getPreciocompra() == castOther.getPreciocompra()) || (this
						.getPreciocompra() != null
						&& castOther.getPreciocompra() != null && this
						.getPreciocompra().equals(castOther.getPreciocompra())))
				&& ((this.getPrecioasesor() == castOther.getPrecioasesor()) || (this
						.getPrecioasesor() != null
						&& castOther.getPrecioasesor() != null && this
						.getPrecioasesor().equals(castOther.getPrecioasesor())))
				&& ((this.getUsuariomod() == castOther.getUsuariomod()) || (this
						.getUsuariomod() != null
						&& castOther.getUsuariomod() != null && this
						.getUsuariomod().equals(castOther.getUsuariomod())))
				&& ((this.getFechamod() == castOther.getFechamod()) || (this
						.getFechamod() != null
						&& castOther.getFechamod() != null && this
						.getFechamod().equals(castOther.getFechamod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37
				* result
				+ (getPreciobolivar() == null ? 0 : this.getPreciobolivar()
						.hashCode());
		result = 37
				* result
				+ (getTipobolivar() == null ? 0 : this.getTipobolivar()
						.hashCode());
		result = 37
				* result
				+ (getValorbolivar() == null ? 0 : this.getValorbolivar()
						.hashCode());
		result = 37 * result
				+ (getNumcuenta() == null ? 0 : this.getNumcuenta().hashCode());
		result = 37
				* result
				+ (getNumcuentapromotor() == null ? 0 : this
						.getNumcuentapromotor().hashCode());
		result = 37
				* result
				+ (getDocumentopromotor() == null ? 0 : this
						.getDocumentopromotor().hashCode());
		result = 37
				* result
				+ (getPreciocompra() == null ? 0 : this.getPreciocompra()
						.hashCode());
		result = 37
				* result
				+ (getPrecioasesor() == null ? 0 : this.getPrecioasesor()
						.hashCode());
		result = 37
				* result
				+ (getUsuariomod() == null ? 0 : this.getUsuariomod()
						.hashCode());
		result = 37 * result
				+ (getFechamod() == null ? 0 : this.getFechamod().hashCode());
		return result;
	}

}
