package org.domain.moneda.entity;

// Generated 7/10/2015 05:14:39 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AuditGastos generated by hbm2java
 */
@Entity
@Table(name = "audit_gastos")
public class AuditGastos implements java.io.Serializable {

	private AuditGastosId id;

	public AuditGastos() {
	}

	public AuditGastos(AuditGastosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "documento", column = @Column(name = "documento", length = 15)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 13)),
			@AttributeOverride(name = "valor", column = @Column(name = "valor", precision = 14, scale = 0)),
			@AttributeOverride(name = "observacion", column = @Column(name = "observacion", length = 200)),
			@AttributeOverride(name = "tipogasto", column = @Column(name = "tipogasto", length = 2)),
			@AttributeOverride(name = "consecutivo", column = @Column(name = "consecutivo", nullable = false)),
			@AttributeOverride(name = "valorbolivar", column = @Column(name = "valorbolivar", precision = 5, scale = 3)),
			@AttributeOverride(name = "usuariomod", column = @Column(name = "usuariomod", length = 20)),
			@AttributeOverride(name = "fechamod", column = @Column(name = "fechamod", length = 22)) })
	@NotNull
	public AuditGastosId getId() {
		return this.id;
	}

	public void setId(AuditGastosId id) {
		this.id = id;
	}

}
