package org.domain.moneda.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco", schema = "public")
public class Banco implements java.io.Serializable {

	private String codbanco;
	private String nombrebanco;
	private Byte dias;	
	private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);
	private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);
	private Set<Cuentapromotor> cuentapromotors = new HashSet<Cuentapromotor>(0);
	private Set<Activacion> activacions = new HashSet<Activacion>(0);
	private Boolean activo;
	

	public Banco() {
	}

	public Banco(String codbanco, String nombrebanco) {
		this.codbanco = codbanco;
		this.nombrebanco = nombrebanco;
	}

	public Banco(String codbanco, String nombrebanco, Byte dias, 
			Set<Cuentapromotor> cuentapromotors, 
			Set<Cuenta> cuentas, Set<Tarjeta> tarjetas,
			Set<Activacion> activacions,
			Boolean activo) {
		this.codbanco = codbanco;
		this.nombrebanco = nombrebanco;
		this.tarjetas = tarjetas;
		this.dias = dias;
		this.cuentas = cuentas;
		this.cuentapromotors = cuentapromotors;
		this.activacions = activacions;
		this.activo = activo;
	}

	@Id
	@Column(name = "codbanco", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodbanco() {
		return this.codbanco;
	}

	public void setCodbanco(String codbanco) {
		this.codbanco = codbanco;
	}

	@Column(name = "nombrebanco", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombrebanco() {
		return this.nombrebanco;
	}

	public void setNombrebanco(String nombrebanco) {
		this.nombrebanco = nombrebanco;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	public Set<Tarjeta> getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Set<Tarjeta> tarjetas) {
		this.tarjetas = tarjetas;
	}
	
	@Column(name = "dias", precision = 2, scale = 0)
	public Byte getDias() {
		return this.dias;
	}

	public void setDias(Byte dias) {
		this.dias = dias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	@OrderBy("nombre")
	public Set<Cuenta> getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set<Cuenta> cuentas) {
		this.cuentas = cuentas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	public Set<Cuentapromotor> getCuentapromotors() {
		return this.cuentapromotors;
	}

	public void setCuentapromotors(Set<Cuentapromotor> cuentapromotors) {
		this.cuentapromotors = cuentapromotors;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	public Set<Activacion> getActivacions() {
		return this.activacions;
	}

	public void setActivacions(Set<Activacion> activacions) {
		this.activacions = activacions;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}	
	
}
