package org.domain.moneda.entity;

// Generated 31/01/2012 05:11:45 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Bancocol generated by hbm2java
 */
@Entity
@Table(name = "bancocol", schema = "public")
public class Bancocol implements java.io.Serializable {

	private String codbanco;
	private String nombre;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);

	public Bancocol() {
	}

	public Bancocol(String codbanco) {
		this.codbanco = codbanco;
	}

	public Bancocol(String codbanco, String nombre,
			Set<Establecimiento> establecimientos) {
		this.codbanco = codbanco;
		this.nombre = nombre;
		this.establecimientos = establecimientos;
	}

	@Id
	@Column(name = "codbanco", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodbanco() {
		return this.codbanco;
	}

	public void setCodbanco(String codbanco) {
		this.codbanco = codbanco;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bancocol")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

}
