package org.domain.moneda.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", schema = "public")
public class Cargo implements java.io.Serializable {

	private String codcargo;
	private String nombrecargo;
	private Set<Personal> personals = new HashSet<Personal>(0);

	public Cargo() {
	}

	public Cargo(String codcargo) {
		this.codcargo = codcargo;
	}

	public Cargo(String codcargo, String nombrecargo, Set<Personal> personals) {
		this.codcargo = codcargo;
		this.nombrecargo = nombrecargo;
		this.personals = personals;
	}

	@Id
	@Column(name = "codcargo", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getCodcargo() {
		return this.codcargo;
	}

	public void setCodcargo(String codcargo) {
		this.codcargo = codcargo;
	}

	@Column(name = "nombrecargo", length = 50)
	@Length(max = 50)
	public String getNombrecargo() {
		return this.nombrecargo;
	}

	public void setNombrecargo(String nombrecargo) {
		this.nombrecargo = nombrecargo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Personal> getPersonals() {
		return this.personals;
	}

	public void setPersonals(Set<Personal> personals) {
		this.personals = personals;
	}

}
