package org.domain.moneda.entity;

// Generated 30/10/2013 10:52:03 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Cnedireccion generated by hbm2java
 */
@Entity
@Table(name = "cnedireccion")
public class Cnedireccion implements java.io.Serializable {

	private CnedireccionId id;

	public Cnedireccion() {
	}

	public Cnedireccion(CnedireccionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codCentro", column = @Column(name = "cod_centro", nullable = false, length = 10)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", length = 3)),
			@AttributeOverride(name = "codEstado", column = @Column(name = "cod_estado", length = 3)),
			@AttributeOverride(name = "codMunicipio", column = @Column(name = "cod_municipio", length = 3)),
			@AttributeOverride(name = "codParroquia", column = @Column(name = "cod_parroquia", length = 3)),
			@AttributeOverride(name = "nombreCentro", column = @Column(name = "nombre_centro", length = 300)),
			@AttributeOverride(name = "direccionCentro", column = @Column(name = "direccion_centro", length = 300)),
			@AttributeOverride(name = "centroNuevo", column = @Column(name = "centro_nuevo", length = 15)) })
	@NotNull
	public CnedireccionId getId() {
		return this.id;
	}

	public void setId(CnedireccionId id) {
		this.id = id;
	}

}
