package org.domain.moneda.entity;

// Generated 30/10/2013 10:52:03 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CnedireccionId generated by hbm2java
 */
@Embeddable
public class CnedireccionId implements java.io.Serializable {

	private String codCentro;
	private String tipo;
	private String codEstado;
	private String codMunicipio;
	private String codParroquia;
	private String nombreCentro;
	private String direccionCentro;
	private String centroNuevo;

	public CnedireccionId() {
	}

	public CnedireccionId(String codCentro) {
		this.codCentro = codCentro;
	}

	public CnedireccionId(String codCentro, String tipo, String codEstado,
			String codMunicipio, String codParroquia, String nombreCentro,
			String direccionCentro, String centroNuevo) {
		this.codCentro = codCentro;
		this.tipo = tipo;
		this.codEstado = codEstado;
		this.codMunicipio = codMunicipio;
		this.codParroquia = codParroquia;
		this.nombreCentro = nombreCentro;
		this.direccionCentro = direccionCentro;
		this.centroNuevo = centroNuevo;
	}

	@Column(name = "cod_centro", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(String codCentro) {
		this.codCentro = codCentro;
	}

	@Column(name = "tipo", length = 3)
	@Length(max = 3)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "cod_estado", length = 3)
	@Length(max = 3)
	public String getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(String codEstado) {
		this.codEstado = codEstado;
	}

	@Column(name = "cod_municipio", length = 3)
	@Length(max = 3)
	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	@Column(name = "cod_parroquia", length = 3)
	@Length(max = 3)
	public String getCodParroquia() {
		return this.codParroquia;
	}

	public void setCodParroquia(String codParroquia) {
		this.codParroquia = codParroquia;
	}

	@Column(name = "nombre_centro", length = 300)
	@Length(max = 300)
	public String getNombreCentro() {
		return this.nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	@Column(name = "direccion_centro", length = 300)
	@Length(max = 300)
	public String getDireccionCentro() {
		return this.direccionCentro;
	}

	public void setDireccionCentro(String direccionCentro) {
		this.direccionCentro = direccionCentro;
	}

	@Column(name = "centro_nuevo", length = 15)
	@Length(max = 15)
	public String getCentroNuevo() {
		return this.centroNuevo;
	}

	public void setCentroNuevo(String centroNuevo) {
		this.centroNuevo = centroNuevo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CnedireccionId))
			return false;
		CnedireccionId castOther = (CnedireccionId) other;

		return ((this.getCodCentro() == castOther.getCodCentro()) || (this
				.getCodCentro() != null
				&& castOther.getCodCentro() != null && this.getCodCentro()
				.equals(castOther.getCodCentro())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())))
				&& ((this.getCodEstado() == castOther.getCodEstado()) || (this
						.getCodEstado() != null
						&& castOther.getCodEstado() != null && this
						.getCodEstado().equals(castOther.getCodEstado())))
				&& ((this.getCodMunicipio() == castOther.getCodMunicipio()) || (this
						.getCodMunicipio() != null
						&& castOther.getCodMunicipio() != null && this
						.getCodMunicipio().equals(castOther.getCodMunicipio())))
				&& ((this.getCodParroquia() == castOther.getCodParroquia()) || (this
						.getCodParroquia() != null
						&& castOther.getCodParroquia() != null && this
						.getCodParroquia().equals(castOther.getCodParroquia())))
				&& ((this.getNombreCentro() == castOther.getNombreCentro()) || (this
						.getNombreCentro() != null
						&& castOther.getNombreCentro() != null && this
						.getNombreCentro().equals(castOther.getNombreCentro())))
				&& ((this.getDireccionCentro() == castOther
						.getDireccionCentro()) || (this.getDireccionCentro() != null
						&& castOther.getDireccionCentro() != null && this
						.getDireccionCentro().equals(
								castOther.getDireccionCentro())))
				&& ((this.getCentroNuevo() == castOther.getCentroNuevo()) || (this
						.getCentroNuevo() != null
						&& castOther.getCentroNuevo() != null && this
						.getCentroNuevo().equals(castOther.getCentroNuevo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodCentro() == null ? 0 : this.getCodCentro().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result
				+ (getCodEstado() == null ? 0 : this.getCodEstado().hashCode());
		result = 37
				* result
				+ (getCodMunicipio() == null ? 0 : this.getCodMunicipio()
						.hashCode());
		result = 37
				* result
				+ (getCodParroquia() == null ? 0 : this.getCodParroquia()
						.hashCode());
		result = 37
				* result
				+ (getNombreCentro() == null ? 0 : this.getNombreCentro()
						.hashCode());
		result = 37
				* result
				+ (getDireccionCentro() == null ? 0 : this.getDireccionCentro()
						.hashCode());
		result = 37
				* result
				+ (getCentroNuevo() == null ? 0 : this.getCentroNuevo()
						.hashCode());
		return result;
	}

}
