package org.domain.moneda.entity;

// Generated 14/01/2012 05:26:00 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta", schema = "public")
public class Cuenta implements java.io.Serializable {

	private String numcuenta;
	private Banco banco;
	private String nombre;
	private BigDecimal saldo;
	private Set<Depositostarjeta> depositostarjetas = new HashSet<Depositostarjeta>(0);
	private Set<Cuentacredito> cuentacreditos = new HashSet<Cuentacredito>(0);
	
	private Set<Transferencia> transferencias = new HashSet<Transferencia>(0);


	public Cuenta() {
	}

	public Cuenta(String numcuenta, Banco banco) {
		this.numcuenta = numcuenta;
		this.banco = banco;
	}

	public Cuenta(String numcuenta, Banco banco, String nombre,
			BigDecimal saldo, Set<Depositostarjeta> depositostarjetas,
			Set<Cuentacredito> cuentacreditos,
			 Set<Transferencia> transferencias) {
		this.numcuenta = numcuenta;
		this.banco = banco;
		this.nombre = nombre;
		this.saldo = saldo;
		this.cuentacreditos = cuentacreditos;
		this.depositostarjetas = depositostarjetas;
		this.transferencias = transferencias;
	}

	@Id
	@Column(name = "numcuenta", unique = true, nullable = false, length = 25)
	@NotNull
	@Length(max = 25)
	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codbanco", nullable = false)
	@NotNull
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Column(name = "nombre", length = 100)
	@Length(max = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "saldo", precision = 12)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
	public Set<Depositostarjeta> getDepositostarjetas() {
		return this.depositostarjetas;
	}

	public void setDepositostarjetas(Set<Depositostarjeta> depositostarjetas) {
		this.depositostarjetas = depositostarjetas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
	public Set<Transferencia> getTransferencias() {
		return this.transferencias;
	}

	public void setTransferencias(Set<Transferencia> transferencias) {
		this.transferencias = transferencias;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
	public Set<Cuentacredito> getCuentacreditos() {
		return this.cuentacreditos;
	}

	public void setCuentacreditos(Set<Cuentacredito> cuentacreditos) {
		this.cuentacreditos = cuentacreditos;
	}

}
