package org.domain.moneda.entity;

// Generated 30/10/2013 10:52:03 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Diasemana generated by hbm2java
 */
@Entity
@Table(name = "diasemana")
public class Diasemana implements java.io.Serializable {

	private DiasemanaId id;

	public Diasemana() {
	}

	public Diasemana(DiasemanaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codigodia", column = @Column(name = "codigodia", nullable = false)),
			@AttributeOverride(name = "nombredia", column = @Column(name = "nombredia", length = 15)) })
	@NotNull
	public DiasemanaId getId() {
		return this.id;
	}

	public void setId(DiasemanaId id) {
		this.id = id;
	}

}
