package org.domain.moneda.entity;

// Generated 30/10/2013 10:52:03 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * DiasemanaId generated by hbm2java
 */
@Embeddable
public class DiasemanaId implements java.io.Serializable {

	private int codigodia;
	private String nombredia;

	public DiasemanaId() {
	}

	public DiasemanaId(int codigodia) {
		this.codigodia = codigodia;
	}

	public DiasemanaId(int codigodia, String nombredia) {
		this.codigodia = codigodia;
		this.nombredia = nombredia;
	}

	@Column(name = "codigodia", nullable = false)
	public int getCodigodia() {
		return this.codigodia;
	}

	public void setCodigodia(int codigodia) {
		this.codigodia = codigodia;
	}

	@Column(name = "nombredia", length = 15)
	@Length(max = 15)
	public String getNombredia() {
		return this.nombredia;
	}

	public void setNombredia(String nombredia) {
		this.nombredia = nombredia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiasemanaId))
			return false;
		DiasemanaId castOther = (DiasemanaId) other;

		return (this.getCodigodia() == castOther.getCodigodia())
				&& ((this.getNombredia() == castOther.getNombredia()) || (this
						.getNombredia() != null
						&& castOther.getNombredia() != null && this
						.getNombredia().equals(castOther.getNombredia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigodia();
		result = 37 * result
				+ (getNombredia() == null ? 0 : this.getNombredia().hashCode());
		return result;
	}

}
