package org.domain.moneda.entity;

// Generated 31/01/2012 05:11:45 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FranquiciaestablecimientoId generated by hbm2java
 */
@Embeddable
public class FranquiciaestablecimientoId implements java.io.Serializable {

	private String franquicia;
	private String establecimiento;

	public FranquiciaestablecimientoId() {
	}

	public FranquiciaestablecimientoId(String franquicia, String establecimiento) {
		this.franquicia = franquicia;
		this.establecimiento = establecimiento;
	}

	@Column(name = "franquicia", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(String franquicia) {
		this.franquicia = franquicia;
	}

	@Column(name = "establecimiento", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(String establecimiento) {
		this.establecimiento = establecimiento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FranquiciaestablecimientoId))
			return false;
		FranquiciaestablecimientoId castOther = (FranquiciaestablecimientoId) other;

		return ((this.getFranquicia() == castOther.getFranquicia()) || (this
				.getFranquicia() != null
				&& castOther.getFranquicia() != null && this.getFranquicia()
				.equals(castOther.getFranquicia())))
				&& ((this.getEstablecimiento() == castOther
						.getEstablecimiento()) || (this.getEstablecimiento() != null
						&& castOther.getEstablecimiento() != null && this
						.getEstablecimiento().equals(
								castOther.getEstablecimiento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFranquicia() == null ? 0 : this.getFranquicia()
						.hashCode());
		result = 37
				* result
				+ (getEstablecimiento() == null ? 0 : this.getEstablecimiento()
						.hashCode());
		return result;
	}

}
