package org.domain.moneda.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Franquicia generated by hbm2java
 */
@Entity
@Table(name = "franquicia", schema = "public")
public class Franquicia implements java.io.Serializable {

	private String codfranquicia;
	private String nombrefranquicia;
	private BigDecimal porcentaje;
	private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);
	private Set<Franquiciaestablecimiento> franquiciaestablecimientos = new HashSet<Franquiciaestablecimiento>(
			0);
	private Set<Promotorfranquicia> promotorfranquicias = new HashSet<Promotorfranquicia>(
			0);

	public Franquicia() {
	}

	public Franquicia(String codfranquicia, String nombrefranquicia) {
		this.codfranquicia = codfranquicia;
		this.nombrefranquicia = nombrefranquicia;
	}

	public Franquicia(String codfranquicia, String nombrefranquicia,
			BigDecimal porcentaje, Set<Franquiciaestablecimiento> franquiciaestablecimientos,
			Set<Tarjeta> tarjetas, Set<Promotorfranquicia> promotorfranquicias) {
		this.codfranquicia = codfranquicia;
		this.nombrefranquicia = nombrefranquicia;
		this.franquiciaestablecimientos = franquiciaestablecimientos;
		this.tarjetas = tarjetas;
		this.promotorfranquicias = promotorfranquicias;
	}

	@Id
	@Column(name = "codfranquicia", unique = true, nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getCodfranquicia() {
		return this.codfranquicia;
	}

	public void setCodfranquicia(String codfranquicia) {
		this.codfranquicia = codfranquicia;
	}

	@Column(name = "nombrefranquicia", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombrefranquicia() {
		return this.nombrefranquicia;
	}

	public void setNombrefranquicia(String nombrefranquicia) {
		this.nombrefranquicia = nombrefranquicia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Tarjeta> getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Set<Tarjeta> tarjetas) {
		this.tarjetas = tarjetas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Franquiciaestablecimiento> getFranquiciaestablecimientos() {
		return this.franquiciaestablecimientos;
	}

	public void setFranquiciaestablecimientos(
			Set<Franquiciaestablecimiento> franquiciaestablecimientos) {
		this.franquiciaestablecimientos = franquiciaestablecimientos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Promotorfranquicia> getPromotorfranquicias() {
		return this.promotorfranquicias;
	}

	public void setPromotorfranquicias(
			Set<Promotorfranquicia> promotorfranquicias) {
		this.promotorfranquicias = promotorfranquicias;
	}
	
	@Column(name = "porcentaje", precision = 5, scale = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
