package org.domain.moneda.entity;

// Generated 31/01/2012 05:11:45 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Franquiciaestablecimiento generated by hbm2java
 */
@Entity
@Table(name = "franquiciaestablecimiento", schema = "public")
public class Franquiciaestablecimiento implements java.io.Serializable {

	private FranquiciaestablecimientoId id;
	private Franquicia franquicia;
	private Establecimiento establecimiento;
	private BigDecimal porcentaje;

	public Franquiciaestablecimiento() {
	}

	public Franquiciaestablecimiento(FranquiciaestablecimientoId id,
			Franquicia franquicia, Establecimiento establecimiento) {
		this.id = id;
		this.franquicia = franquicia;
		this.establecimiento = establecimiento;
	}

	public Franquiciaestablecimiento(FranquiciaestablecimientoId id,
			Franquicia franquicia, Establecimiento establecimiento,
			BigDecimal porcentaje) {
		this.id = id;
		this.franquicia = franquicia;
		this.establecimiento = establecimiento;
		this.porcentaje = porcentaje;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "franquicia", column = @Column(name = "franquicia", nullable = false, length = 1)),
			@AttributeOverride(name = "establecimiento", column = @Column(name = "establecimiento", nullable = false, length = 8)) })
	@NotNull
	public FranquiciaestablecimientoId getId() {
		return this.id;
	}

	public void setId(FranquiciaestablecimientoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "franquicia", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Franquicia getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(Franquicia franquicia) {
		this.franquicia = franquicia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "establecimiento", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	@Column(name = "porcentaje", precision = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
