package org.domain.moneda.entity;

// Generated 31/01/2012 05:11:45 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Gravamen generated by hbm2java
 */
@Entity
@Table(name = "gravamen", schema = "public")
public class Gravamen implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private BigDecimal porcentaje;
	private Boolean iva;
	private Set<Gravamenestablecimiento> gravamenestablecimientos = new HashSet<Gravamenestablecimiento>(
			0);

	public Gravamen() {
	}

	public Gravamen(String codigo) {
		this.codigo = codigo;
	}

	public Gravamen(String codigo, String nombre, BigDecimal porcentaje,
			Boolean iva,
			Set<Gravamenestablecimiento> gravamenestablecimientos) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.porcentaje = porcentaje;
		this.gravamenestablecimientos = gravamenestablecimientos;
		this.iva = iva;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", length = 30)
	@Length(max = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", precision = 5, scale = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "iva")
	public Boolean getIva() {
		return this.iva;
	}

	public void setIva(Boolean iva) {
		this.iva = iva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gravamen")
	public Set<Gravamenestablecimiento> getGravamenestablecimientos() {
		return this.gravamenestablecimientos;
	}

	public void setGravamenestablecimientos(
			Set<Gravamenestablecimiento> gravamenestablecimientos) {
		this.gravamenestablecimientos = gravamenestablecimientos;
	}
	
}
