package org.domain.moneda.entity;

// Generated 27/04/2015 11:47:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Mesanio generated by hbm2java
 */
@Entity
@Table(name = "mesanio")
public class Mesanio implements java.io.Serializable {

	private int codigomes;
	private String nombremes;

	public Mesanio() {
	}

	public Mesanio(int codigomes) {
		this.codigomes = codigomes;
	}

	public Mesanio(int codigomes, String nombremes) {
		this.codigomes = codigomes;
		this.nombremes = nombremes;
	}

	@Id
	@Column(name = "codigomes", unique = true, nullable = false)
	public int getCodigomes() {
		return this.codigomes;
	}

	public void setCodigomes(int codigomes) {
		this.codigomes = codigomes;
	}

	@Column(name = "nombremes", length = 12)
	@Length(max = 12)
	public String getNombremes() {
		return this.nombremes;
	}

	public void setNombremes(String nombremes) {
		this.nombremes = nombremes;
	}

}
