package org.domain.moneda.entity;

// Generated 7/10/2015 05:14:39 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "moneda")
public class Moneda implements java.io.Serializable {

	private String codigomoneda;
	private String nombreMoneda;
	

	public Moneda() {
	}

	public Moneda(String codigomoneda) {
		this.codigomoneda = codigomoneda;
	}

	public Moneda(String codigomoneda, String nombreMoneda) {
		this.codigomoneda = codigomoneda;
		this.nombreMoneda = nombreMoneda;
		
	}

	@Id
	@Column(name = "codigomoneda", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigomoneda() {
		return this.codigomoneda;
	}

	public void setCodigomoneda(String codigomoneda) {
		this.codigomoneda = codigomoneda;
	}

	@Column(name = "nombre_moneda", length = 60)
	@Length(max = 60)
	public String getNombreMoneda() {
		return this.nombreMoneda;
	}

	public void setNombreMoneda(String nombreMoneda) {
		this.nombreMoneda = nombreMoneda;
	}

	
}
