package org.domain.moneda.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", schema = "public")
public class Pais implements java.io.Serializable {

	private String codigopais;
	private Paisiso paisiso;
	private String nombre;
	//private Boolean estado;
	private Set<Promotorcomisiontx> promotorcomisiontxes = new HashSet<Promotorcomisiontx>(
			0);
	private Set<Porcentajecomisiontx> porcentajecomisiontxes = new HashSet<Porcentajecomisiontx>(
			0);
	private Set<Tasadolarpromotorparametro> tasadolarpromotorparametros = new HashSet<Tasadolarpromotorparametro>(
			0);
	private Set<Tasadolarpromotorparametro> tasadolarpromotorparametros_1 = new HashSet<Tasadolarpromotorparametro>(
			0);
	private Set<Promotortasa> promotortasas = new HashSet<Promotortasa>(0);
	private Set<Porcentajecomisiontx> porcentajecomisiontxes_1 = new HashSet<Porcentajecomisiontx>(
			0);
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);
	private Set<Establecimiento> establecimientos_1 = new HashSet<Establecimiento>(
			0);
	private Set<Tasadolar> tasadolars = new HashSet<Tasadolar>(0);
	private Set<Promotorcomisiontx> promotorcomisiontxes_1 = new HashSet<Promotorcomisiontx>(
			0);
	private Set<Promotortasa> promotortasas_1 = new HashSet<Promotortasa>(0);
	private Set<Tasadolar> tasadolars_1 = new HashSet<Tasadolar>(0);
	
	public Pais() {
	}

	public Pais(String codigopais) {
		this.codigopais = codigopais;
	}

	public Pais(String codigopais, Paisiso paisiso, String nombre,
			Boolean estado, Set<Promotorcomisiontx> promotorcomisiontxes,
			Set<Porcentajecomisiontx> porcentajecomisiontxes,
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros,
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros_1,
			Set<Promotortasa> promotortasas,
			Set<Porcentajecomisiontx> porcentajecomisiontxes_1,
			Set<Establecimiento> establecimientos,
			Set<Establecimiento> establecimientos_1,
			Set<Tasadolar> tasadolars,
			Set<Promotorcomisiontx> promotorcomisiontxes_1,
			Set<Promotortasa> promotortasas_1,
			Set<Tasadolar> tasadolars_1){
		this.codigopais = codigopais;
		this.paisiso = paisiso;
		this.nombre = nombre;
	//	this.estado = estado;
		this.promotorcomisiontxes = promotorcomisiontxes;
		this.porcentajecomisiontxes = porcentajecomisiontxes;
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
		this.tasadolarpromotorparametros_1 = tasadolarpromotorparametros_1;
		this.promotortasas = promotortasas;
		this.porcentajecomisiontxes_1 = porcentajecomisiontxes_1;
		this.establecimientos = establecimientos;
		this.establecimientos_1 = establecimientos_1;
		this.tasadolars = tasadolars;
		this.promotorcomisiontxes_1 = promotorcomisiontxes_1;
		this.promotortasas_1 = promotortasas_1;
		this.tasadolars_1 = tasadolars_1;
		
	}

	@Id
	@Column(name = "codigopais", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigopaisiso")
	public Paisiso getPaisiso() {
		return this.paisiso;
	}

	public void setPaisiso(Paisiso paisiso) {
		this.paisiso = paisiso;
	}

	@Column(name = "nombre", length = 25)
	@Length(max = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/*@Column(name = "estado", precision = 1, scale = 0)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Promotorcomisiontx> getPromotorcomisiontxes() {
		return this.promotorcomisiontxes;
	}

	public void setPromotorcomisiontxes(
			Set<Promotorcomisiontx> promotorcomisiontxes) {
		this.promotorcomisiontxes = promotorcomisiontxes;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Porcentajecomisiontx> getPorcentajecomisiontxes() {
		return this.porcentajecomisiontxes;
	}

	public void setPorcentajecomisiontxes(
			Set<Porcentajecomisiontx> porcentajecomisiontxes) {
		this.porcentajecomisiontxes = porcentajecomisiontxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolarpromotorparametro> getTasadolarpromotorparametros() {
		return this.tasadolarpromotorparametros;
	}

	public void setTasadolarpromotorparametros(
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros) {
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolarpromotorparametro> getTasadolarpromotorparametros_1() {
		return this.tasadolarpromotorparametros_1;
	}

	public void setTasadolarpromotorparametros_1(
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros_1) {
		this.tasadolarpromotorparametros_1 = tasadolarpromotorparametros_1;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Promotortasa> getPromotortasas() {
		return this.promotortasas;
	}

	public void setPromotortasas(Set<Promotortasa> promotortasas) {
		this.promotortasas = promotortasas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Porcentajecomisiontx> getPorcentajecomisiontxes_1() {
		return this.porcentajecomisiontxes_1;
	}

	public void setPorcentajecomisiontxes_1(
			Set<Porcentajecomisiontx> porcentajecomisiontxes_1) {
		this.porcentajecomisiontxes_1 = porcentajecomisiontxes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Establecimiento> getEstablecimientos_1() {
		return this.establecimientos_1;
	}

	public void setEstablecimientos_1(Set<Establecimiento> establecimientos_1) {
		this.establecimientos_1 = establecimientos_1;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolar> getTasadolars() {
		return this.tasadolars;
	}

	public void setTasadolars(Set<Tasadolar> tasadolars) {
		this.tasadolars = tasadolars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Promotorcomisiontx> getPromotorcomisiontxes_1() {
		return this.promotorcomisiontxes_1;
	}

	public void setPromotorcomisiontxes_1(
			Set<Promotorcomisiontx> promotorcomisiontxes_1) {
		this.promotorcomisiontxes_1 = promotorcomisiontxes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Promotortasa> getPromotortasas_1() {
		return this.promotortasas_1;
	}

	public void setPromotortasas_1(Set<Promotortasa> promotortasas_1) {
		this.promotortasas_1 = promotortasas_1;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolar> getTasadolars_1() {
		return this.tasadolars_1;
	}

	public void setTasadolars_1(Set<Tasadolar> tasadolars_1) {
		this.tasadolars_1 = tasadolars_1;
	}

	
}
