package org.domain.moneda.entity;

// Generated 7/10/2015 05:14:39 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Porcentajeparametros generated by hbm2java
 */
@Entity
@Table(name = "porcentajeparametros")
public class Porcentajeparametros implements java.io.Serializable {

	private PorcentajeparametrosId id;
	private Franquicia franquicia;
	private Pais pais;
	private Banco banco;
	private Date fechafin;
	private Short porcentaje;

	public Porcentajeparametros() {
	}

	public Porcentajeparametros(PorcentajeparametrosId id,
			Franquicia franquicia, Pais pais, Banco banco) {
		this.id = id;
		this.franquicia = franquicia;
		this.pais = pais;
		this.banco = banco;
	}

	public Porcentajeparametros(PorcentajeparametrosId id,
			Franquicia franquicia, Pais pais, Banco banco, Date fechafin,
			Short porcentaje) {
		this.id = id;
		this.franquicia = franquicia;
		this.pais = pais;
		this.banco = banco;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codbanco", column = @Column(name = "codbanco", nullable = false, length = 3)),
			@AttributeOverride(name = "codfranquicia", column = @Column(name = "codfranquicia", nullable = false, length = 1)),
			@AttributeOverride(name = "codpais", column = @Column(name = "codpais", nullable = false, length = 5)),
			@AttributeOverride(name = "fechainicio", column = @Column(name = "fechainicio", nullable = false, length = 29)) })
	@NotNull
	public PorcentajeparametrosId getId() {
		return this.id;
	}

	public void setId(PorcentajeparametrosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codfranquicia", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Franquicia getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(Franquicia franquicia) {
		this.franquicia = franquicia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codpais", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codbanco", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "porcentaje", precision = 4, scale = 0)
	public Short getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Short porcentaje) {
		this.porcentaje = porcentaje;
	}

}
