package org.domain.moneda.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Puntodeventa generated by hbm2java
 */
@Entity
@Table(name = "puntodeventa", schema = "public")
public class Puntodeventa implements java.io.Serializable {

	private String codpuntoventa;
	private String nombre;
	

	public Puntodeventa() {
	}

	public Puntodeventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	public Puntodeventa(String codpuntoventa, String nombre) {
		this.codpuntoventa = codpuntoventa;
		this.nombre = nombre;
		
	}

	@Id
	@Column(name = "codpuntoventa", unique = true, nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getCodpuntoventa() {
		return this.codpuntoventa;
	}

	public void setCodpuntoventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}



}
