package org.domain.moneda.entity;

// Generated 16/11/2012 06:17:05 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Reportes generated by hbm2java
 */
@Entity
@Table(name = "reportes", schema = "public")
public class Reportes implements java.io.Serializable {

	private String codreporte;
	private String descripcion;
	private Short parametros;

	public Reportes() {
	}

	public Reportes(String codreporte) {
		this.codreporte = codreporte;
	}

	public Reportes(String codreporte, String descripcion, Short parametros) {
		this.codreporte = codreporte;
		this.descripcion = descripcion;
		this.parametros = parametros;
	}

	@Id
	@Column(name = "codreporte", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCodreporte() {
		return this.codreporte;
	}

	public void setCodreporte(String codreporte) {
		this.codreporte = codreporte;
	}

	@Column(name = "descripcion", length = 100)
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "parametros", precision = 3, scale = 0)
	public Short getParametros() {
		return this.parametros;
	}

	public void setParametros(Short parametros) {
		this.parametros = parametros;
	}

}
