package org.domain.moneda.entity;

// Generated 27/04/2015 11:47:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Sales generated by hbm2java
 */
@Entity
@Table(name = "sales")
public class Sales implements java.io.Serializable {

	private SalesId id;

	public Sales() {
	}

	public Sales(SalesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "year", column = @Column(name = "year")),
			@AttributeOverride(name = "month", column = @Column(name = "month")),
			@AttributeOverride(name = "qty", column = @Column(name = "qty")) })
	public SalesId getId() {
		return this.id;
	}

	public void setId(SalesId id) {
		this.id = id;
	}

}
