package org.domain.moneda.entity;

// Generated 7/10/2015 05:14:39 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * Tasadolarbancopais generated by hbm2java
 */
@Entity
@Table(name = "tasadolarbancopais", uniqueConstraints = @UniqueConstraint(columnNames = "fecha"))
public class Tasadolarbancopais implements java.io.Serializable {

	private TasadolarbancopaisId id;
	private Pais pais;
	private Banco banco;
	private Integer tasacliente;
	private Integer tasaoficina;

	public Tasadolarbancopais() {
	}

	public Tasadolarbancopais(TasadolarbancopaisId id, Pais pais, Banco banco) {
		this.id = id;
		this.pais = pais;
		this.banco = banco;
	}

	public Tasadolarbancopais(TasadolarbancopaisId id, Pais pais, Banco banco,
			Integer tasacliente, Integer tasaoficina) {
		this.id = id;
		this.pais = pais;
		this.banco = banco;
		this.tasacliente = tasacliente;
		this.tasaoficina = tasaoficina;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codbanco", column = @Column(name = "codbanco", nullable = false, length = 3)),
			@AttributeOverride(name = "codigopais", column = @Column(name = "codigopais", nullable = false, length = 5)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", unique = true, nullable = false, length = 29)) })
	@NotNull
	public TasadolarbancopaisId getId() {
		return this.id;
	}

	public void setId(TasadolarbancopaisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigopais", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codbanco", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Column(name = "tasacliente", precision = 6, scale = 0)
	public Integer getTasacliente() {
		return this.tasacliente;
	}

	public void setTasacliente(Integer tasacliente) {
		this.tasacliente = tasacliente;
	}

	@Column(name = "tasaoficina", precision = 6, scale = 0)
	public Integer getTasaoficina() {
		return this.tasaoficina;
	}

	public void setTasaoficina(Integer tasaoficina) {
		this.tasaoficina = tasaoficina;
	}

}
