package org.domain.moneda.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Tasadolar generated by hbm2java
 */
@Entity
@Table(name = "tasadolar", schema = "public")
public class Tasadolar implements java.io.Serializable {

	private TasadolarId id;
	private Pais pais;
	private BigDecimal tasa;
	private BigDecimal tasadolar;

	public Tasadolar() {
	}

	public Tasadolar(TasadolarId id, Pais pais) {
		this.id = id;
		this.pais = pais;
	}

	public Tasadolar(TasadolarId id, Pais pais, BigDecimal tasa, BigDecimal tasadolar) {
		this.id = id;
		this.pais = pais;
		this.tasa = tasa;
		this.tasadolar = tasadolar;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codigopais", column = @Column(name = "codigopais", nullable = false, length = 5)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 29)) })
	@NotNull
	public TasadolarId getId() {
		return this.id;
	}

	public void setId(TasadolarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigopais", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "tasa", precision = 6)
	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}
	
	@Column(name = "tasadolar", precision = 6)
	public BigDecimal getTasadolar() {
		return this.tasadolar;
	}

	public void setTasadolar(BigDecimal tasadolar) {
		this.tasadolar = tasadolar;
	}

}
