package org.domain.moneda.entity;

// Generated 31/03/2012 04:11:21 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Tasabolivarnegociado generated by hbm2java
 */
@Entity
@Table(name = "tasabolivarnegociado", schema = "public")
public class Tasabolivarnegociado implements java.io.Serializable {

	private TasabolivarnegociadoId id;
	private Promotor promotor;
	private BigDecimal preciobolivar;
	private BigDecimal preciocompra;
	private BigDecimal precioasesor;

	public Tasabolivarnegociado() {
	}

	public Tasabolivarnegociado(TasabolivarnegociadoId id, Promotor promotor,
			BigDecimal preciobolivar, BigDecimal preciocompra, BigDecimal precioasesor) {
		this.id = id;
		this.promotor = promotor;
		this.preciobolivar = preciobolivar;
		this.preciocompra = preciocompra;
		this.precioasesor = precioasesor;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 13)),
			@AttributeOverride(name = "documento", column = @Column(name = "documento", nullable = false, length = 15)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", nullable = false, length = 1)) })
	@NotNull
	public TasabolivarnegociadoId getId() {
		return this.id;
	}

	public void setId(TasabolivarnegociadoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	@Column(name = "preciobolivar", nullable = false, precision = 5)
	@NotNull
	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}
	
	@Column(name = "preciocompra", nullable = false, precision = 5)
	@NotNull
	public BigDecimal getPreciocompra() {
		return preciocompra;
	}
	
	public void setPreciocompra(BigDecimal preciocompra) {
		this.preciocompra = preciocompra;
	}
	
	@Column(name = "precioasesor", nullable = false, precision = 5)
	@NotNull
	public BigDecimal getPrecioasesor() {
		return precioasesor;
	}

	public void setPrecioasesor(BigDecimal precioasesor) {
		this.precioasesor = precioasesor;
	}
	
	

}
