package org.domain.moneda.entity;

// Generated 31/01/2012 05:11:45 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tipoproceso generated by hbm2java
 */
@Entity
@Table(name = "tipoproceso", schema = "public")
public class Tipoproceso implements java.io.Serializable {

	private String tipo;
	private String descripcion;
	private Set<Personaltipoproceso> personaltipoprocesos = new HashSet<Personaltipoproceso>(
			0);

	public Tipoproceso() {
	}

	public Tipoproceso(String tipo) {
		this.tipo = tipo;
	}

	public Tipoproceso(String tipo, String descripcion,
			Set<Personaltipoproceso> personaltipoprocesos) {
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.personaltipoprocesos = personaltipoprocesos;
	}

	@Id
	@Column(name = "tipo", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "descripcion", length = 50)
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoproceso")
	public Set<Personaltipoproceso> getPersonaltipoprocesos() {
		return this.personaltipoprocesos;
	}

	public void setPersonaltipoprocesos(
			Set<Personaltipoproceso> personaltipoprocesos) {
		this.personaltipoprocesos = personaltipoprocesos;
	}

}
