package org.domain.moneda.entity;

// Generated 31/03/2012 10:44:55 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Transferencia generated by hbm2java
 */
@Entity
@Table(name = "transferencia", schema = "public")
public class Transferencia implements java.io.Serializable {

	private int consecutivo;
	private Gastos gastos;
	private Cuenta cuenta;
	private BigDecimal valorbolivar;
	private BigDecimal preciobolivar;
	private String tipobolivar;
	private Cuentapromotor cuentapromotor;
	private BigDecimal preciocompra;
	private BigDecimal precioasesor;
	private String usuariomod;
	private Date fechamod;

	public Transferencia() {
	}

	public Transferencia(Gastos gastos) {
		this.gastos = gastos;
	}

	public Transferencia(Gastos gastos, Cuenta cuenta, BigDecimal valorbolivar,
			BigDecimal preciobolivar, String tipobolivar,
			Cuentapromotor cuentapromotor, BigDecimal preciocompra, 
			BigDecimal precioasesor, String usuariomod, Date fechamod ) {
		this.gastos = gastos;
		this.cuenta = cuenta;
		this.valorbolivar = valorbolivar;
		this.preciobolivar = preciobolivar;
		this.tipobolivar = tipobolivar;
		this.cuentapromotor = cuentapromotor;
		this.preciocompra = preciocompra;
		this.precioasesor = precioasesor;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "gastos"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "consecutivo", unique = true, nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Gastos getGastos() {
		return this.gastos;
	}

	public void setGastos(Gastos gastos) {
		this.gastos = gastos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numcuenta")
	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "valorbolivar", precision = 12)
	public BigDecimal getValorbolivar() {
		return this.valorbolivar;
	}

	public void setValorbolivar(BigDecimal valorbolivar) {
		this.valorbolivar = valorbolivar;
	}

	@Column(name = "preciobolivar", precision = 5)
	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	@Column(name = "tipobolivar", length = 3)
	@Length(max = 3)
	public String getTipobolivar() {
		return this.tipobolivar;
	}

	public void setTipobolivar(String tipobolivar) {
		this.tipobolivar = tipobolivar;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "numcuentapromotor", referencedColumnName = "numcuenta"),
			@JoinColumn(name = "documentopromotor", referencedColumnName = "documento") })
	public Cuentapromotor getCuentapromotor() {
		return this.cuentapromotor;
	}

	public void setCuentapromotor(Cuentapromotor cuentapromotor) {
		this.cuentapromotor = cuentapromotor;
	}
	
	@Column(name = "preciocompra", nullable = false, precision = 5)

	public BigDecimal getPreciocompra() {
		return preciocompra;
	}
	
	public void setPreciocompra(BigDecimal preciocompra) {
		this.preciocompra = preciocompra;
	}
	
	@Column(name = "precioasesor", nullable = false, precision = 5)
	public BigDecimal getPrecioasesor() {
		return precioasesor;
	}

	public void setPrecioasesor(BigDecimal precioasesor) {
		this.precioasesor = precioasesor;
	}
	
	@Column(name = "usuariomod", nullable = true, length = 20)
	@Length(max = 20)
	public String getUsuariomod() {
		return usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", length = 29)
	public Date getFechamod() {
		return fechamod;
	}

	
	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}
	

}
