package org.domain.moneda.entity;

// Generated 2/03/2013 03:06:19 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variable")
public class Variable implements java.io.Serializable {

	private int numregistro;
	private BigDecimal preciodolarven;

	public Variable() {
	}

	public Variable(int numregistro) {
		this.numregistro = numregistro;
	}

	public Variable(int numregistro, BigDecimal preciodolarven) {
		this.numregistro = numregistro;
		this.preciodolarven = preciodolarven;
	}

	@Id
	@Column(name = "numregistro", unique = true, nullable = false)
	public int getNumregistro() {
		return this.numregistro;
	}

	public void setNumregistro(int numregistro) {
		this.numregistro = numregistro;
	}

	@Column(name = "preciodolarven", precision = 4)
	public BigDecimal getPreciodolarven() {
		return this.preciodolarven;
	}

	public void setPreciodolarven(BigDecimal preciodolarven) {
		this.preciodolarven = preciodolarven;
	}

}
