package org.domain.moneda.entity;
// Generated 27/04/2013 03:28:18 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vistaactivaciones generated by hbm2java
 */
@Entity
@Table(name="vistaactivaciones"
    ,schema="public"
)
public class Vistaactivaciones  implements java.io.Serializable {


	private Integer consecutivo;
	private Date fecha;
	private String estado;
	private String documento;

	public Vistaactivaciones() {
	}

	public Vistaactivaciones(Integer consecutivo, Date fecha, String estado,
			String documento) {
		this.consecutivo = consecutivo;
		this.fecha = fecha;
		this.estado = estado;
		this.documento = documento;
	}
	
	@Id
	@Column(name = "consecutivo")
	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "documento")
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}




}


