package org.domain.moneda.entity;

// Generated 27/04/2015 11:47:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vistasaldoviernes generated by hbm2java
 */
@Entity
@Table(name = "vistasaldoviernes")
public class Vistasaldoviernes implements java.io.Serializable {

	private VistasaldoviernesId id;

	public Vistasaldoviernes() {
	}

	public Vistasaldoviernes(VistasaldoviernesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "docupromo", column = @Column(name = "docupromo", length = 15)),
			@AttributeOverride(name = "nombrepromo", column = @Column(name = "nombrepromo")),
			@AttributeOverride(name = "asesora", column = @Column(name = "asesora")),
			@AttributeOverride(name = "saldoCliente", column = @Column(name = "saldo_cliente", precision = 131089, scale = 0)) })
	public VistasaldoviernesId getId() {
		return this.id;
	}

	public void setId(VistasaldoviernesId id) {
		this.id = id;
	}

}
